### ISSUE TITLE
Support for Blazor server-side/hybrid

### ISSUE THREAD

**Issue by hitec-lbmc** [CamiloTerevinto/TerevintoSoftware.StaticSiteGenerator#8]
I really like this tool and am looking forwarding to using it increasingly in my organization. 

I was wondering if you have any plans to support Blazor apps as well? As in, have the ability to export a Blazor server-side product as a static site. 

Thank you.

**Comment by CamiloTerevinto** [comment]
Hey @hitec-lbmc. As far as I know, there is a way to create an index.html from a Blazor project to get a static site, but I've no idea which of the Blazor mode(s) allows you to do this.

I'm not at all familiar with Blazor, so it's not likely that I'll be able to do this. I'd be happy to accept PRs to add this functionality though :)
